### ISSUE TITLE
"The conditional check 'ansible_default_ipv6.address | length > 0' failed.

### ISSUE THREAD

**Issue by bruvv** [Freekers/ansible-adguard#1]
Nice to see you hopping onto adguard as well, may I ask what your reasons are :)?

I did try and install it on Oracle Cloud but I am getting an error:
```
TASK [Prepare Docker for IPv6] **************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check 'ansible_default_ipv6.address | length > 0' failed. The error was: error while evaluating conditional (ansible_default_ipv6.address | length > 0): 'dict object' has no attribute 'address'\n\nThe error appears to be in '/home/ubuntu/ansible-adguard/playbook.yml': line 86, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Prepare Docker for IPv6\n    ^ here\n"}
```

I never used ansible before but it appears that this recurring line is failing:
```when: ansible_default_ipv6.address | length > 0```

**Comment by Freekers** [comment]
Which OS are you running on the Oracle Cloud VM?

**Comment by bruvv** [comment]
Ubuntu 20.04 LTS (GNU/Linux 5.4.0-1019-oracle x86_64)

**Comment by Freekers** [comment]
Which version of Ansible is installed on the host machine, i.e. the one from which you initiate the playbook?

And does the Oracle Cloud VM have an IPv6 address?

**Comment by bruvv** [comment]
Updated the ubuntu version.

The only ipv6 address there is:
`IPv6 address for docker0:         fd00::1`
other than that I do not have a ipv6 address
```
ansible 2.9.6
python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

**Comment by ghostkernel-core** [comment]
I found out that ignoring the ip6 check fail allows the rest of the playbook to run. Reference to issue #4 

adding this like in the task where ipv6 check is done helps
`ignore_errors: yes`

**Comment by ghostkernel-core** [comment]
I also found out that Ubuntu 18.04 can install ansible version 2.5 from its default repo. with ansible 2.5 the current playbook does work and fails at line 216. To upgrade to ansible 2.9 one needs to add the lauchpad ppa from ansible n then upgrade to the latest ansible inorder to work. I think it is worth mentioning this in the readme file.

```
$ sudo apt install software-properties-common
$ sudo apt-add-repository --yes --update ppa:ansible/ansible
$ sudo apt update
$ sudo apt install ansible
```

**Comment by bruvv** [comment]
https://github.com/Freekers/ansible-adguard/pull/5 should fix this issue @t-abraham thanks.

**Comment by Freekers** [comment]
#5 Is more of a workaround than a fix. I will look if I can get Ansible to reliably detect if IPv6 is available yes or not.
