### ISSUE TITLE
The conditional check 'ansible_default_ipv6.address

### ISSUE THREAD

**Issue by t-abraham** [Freekers/ansible-adguard#4]
Hi, I am having a problem with the installation.
I don't have IPv6 in my cloud VM and once the playbook fails to check IPv6 it does not proceed further.

VM arch: KVM
OS: Ubuntu 20.04 LTS
Ansible Version: 2.9.6

![image](https://user-images.githubusercontent.com/17075361/89700361-d942a280-d92d-11ea-90dc-6361162c32ae.png)

**Comment by bruvv** [comment]
Wow you really didn't look: https://github.com/Freekers/ansible-adguard/issues/1
duplicate

**Comment by t-abraham** [comment]
I saw that but still created to draw attention that others are also having the same problem

**Comment by ghostkernel-core** [comment]
my bad. I thought its a different issue. I am not good with ansible

> 
> 
> Wow you really didn't look: #1
> duplicate

**Comment by ghostkernel-core** [comment]
I found out that ignoring the ip6 check fail allows the rest of the playbook to run.

adding this like in the task where ipv6 check is done helps
`ignore_errors: yes`

**Comment by bruvv** [comment]
can you close this one? and link in this issue: https://github.com/Freekers/ansible-adguard/issues/1 to your PR?
