### ISSUE TITLE
Ran playbook, no luck

### ISSUE THREAD

**Issue by thisisgm** [Freekers/ansible-adguard#9]
I followed the instructions and am not able to connect to the adguard interface after initial setup. Certificates were successfully created but every time I visit adguard.*mydomain*.com I get the Cloudflare notice saying web server down, any ideas as to why? Pretty new to this sorry if this is a noob mistake.

**Comment by Freekers** [comment]
Hey there,

Do you have some logging available of the Docker containers? 
How does your Cloudflare DNS setup/records look like?

**Comment by thisisgm** [comment]
`CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                                                          NAMES
c2417c5c70c2   adguard/adguardhome:latest     "/opt/adguardhome/Ad…"   7 minutes ago   Up 7 minutes                                                                                  adguard-adguard.thisisgm.com
1f08abf0d884   pyouroboros/ouroboros:latest   "ouroboros"              7 minutes ago   Up 7 minutes                                                                                  ouroboros-adguard.thisisgm.com
61f999643762   secns/unbound:latest           "/start.sh"              7 minutes ago   Up 7 minutes   0.0.0.0:5353->53/tcp, 0.0.0.0:5353->53/udp, :::5353->53/tcp, :::5353->53/udp   unbound-adguard.thisisgm.com
aebc1dcfabe0   linuxserver/swag:latest        "/init"                  7 minutes ago   Up 7 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 443/tcp                                     letsencrypt-adguard.thisisgm.com
`
this is my docker ps

**Comment by Freekers** [comment]
Try `docker logs -f adguard-adguard.thisisgm.com`
